# Generated by Django 4.0.6 on 2022-11-18 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('nombre', models.CharField(default='Vacio', max_length=200, verbose_name='nombre')),
                ('apellido', models.CharField(default='Vacio', max_length=200, verbose_name='apellido')),
                ('email', models.EmailField(max_length=200, verbose_name='email')),
                ('rut', models.CharField(default='Vacio', max_length=10, primary_key=True, serialize=False, verbose_name='rut')),
                ('telefono', models.CharField(default='Vacio', max_length=200, verbose_name='telefono')),
                ('ficha', models.TextField(null=True, verbose_name='ficha')),
                ('diab', models.CharField(choices=[['SI', 'Si'], ['NO', 'No']], default='----', max_length=2)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Prof',
            fields=[
                ('nombre', models.CharField(default='Vacio', max_length=200, verbose_name='nombre')),
                ('apellido', models.CharField(default='Vacio', max_length=200, verbose_name='apellido')),
                ('email', models.EmailField(default='Vacio', max_length=200, verbose_name='email')),
                ('id', models.AutoField(default='Vacio', primary_key=True, serialize=False, verbose_name='id_profesional')),
                ('telefono', models.CharField(default='Vacio', max_length=200, verbose_name='telefono')),
                ('ocupacion', models.CharField(default='Vacio', max_length=200, verbose_name='ocupacion')),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Atencion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Vacio', max_length=200, verbose_name='Nombre')),
                ('apellido', models.CharField(default='Vacio', max_length=200, verbose_name='Apellido')),
                ('email', models.EmailField(default='Vacio', max_length=200, verbose_name='Email')),
                ('rut', models.CharField(default='Vacio', max_length=10, verbose_name='Rut')),
                ('telefono', models.CharField(default='Vacio', max_length=200, verbose_name='Telefono')),
                ('diab', models.CharField(choices=[['SI', 'Si'], ['NO', 'No']], default='----', max_length=2)),
                ('fecha', models.DateField(auto_now=True, verbose_name='Fecha')),
                ('hora', models.CharField(choices=[['10:00 a 10:30', '10:00 a 10:30'], ['10:30 a 11:00', '10:30 a 11:00'], ['11:00 a 11:30', '11:00 a 11:30'], ['11:30 a 12:00', '11:30 a 12:00'], ['12:00 a 12:30', '12:00 a 12:30'], ['12:30 a 01:00', '12:30 a 01:00'], ['01:00 a 01:30', '01:00 a 01:30'], ['01:30 a 02:00', '01:30 a 02:00'], ['02:00 a 02:30', '02:00 a 03:30'], ['02:30 a 03:00', '02:00 a 03:30'], ['03:00 a 03:30', '02:00 a 03:30'], ['03:30 a 04:00', '03:30 a 04:00'], ['04:00 a 04:30', '04:00 a 04:30'], ['04:30 a 05:00', '04:30 a 05:00'], ['05:00 a 05:30', '05:00 a 05:30'], ['05:30 a 06:00', '05:30 a 06:00'], ['06:00 a 06:30', '06:00 a 06:30'], ['06:30 a 07:00', '06:30 a 07:00']], default='----', max_length=200)),
                ('coment', models.TextField(default='Vacio', null=True, verbose_name='Comentarios')),
                ('id_prof', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='depil.prof', verbose_name='Atención')),
            ],
            options={
                'ordering': ['fecha'],
            },
        ),
    ]
