# Generated by Django 4.0.6 on 2022-11-18 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depil', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atencion',
            name='apellido',
            field=models.CharField(default='', max_length=200, verbose_name='Apellido'),
        ),
        migrations.AlterField(
            model_name='atencion',
            name='coment',
            field=models.TextField(default='', null=True, verbose_name='Comentarios'),
        ),
        migrations.AlterField(
            model_name='atencion',
            name='email',
            field=models.EmailField(default='', max_length=200, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='atencion',
            name='fecha',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='atencion',
            name='nombre',
            field=models.CharField(default='', max_length=200, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='atencion',
            name='rut',
            field=models.CharField(default='', max_length=10, verbose_name='Rut'),
        ),
        migrations.AlterField(
            model_name='atencion',
            name='telefono',
            field=models.CharField(default='', max_length=200, verbose_name='Telefono'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='apellido',
            field=models.CharField(default='', max_length=200, verbose_name='apellido'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nombre',
            field=models.CharField(default='', max_length=200, verbose_name='nombre'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='rut',
            field=models.CharField(default='', max_length=10, primary_key=True, serialize=False, verbose_name='rut'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(default='', max_length=200, verbose_name='telefono'),
        ),
        migrations.AlterField(
            model_name='prof',
            name='apellido',
            field=models.CharField(default='', max_length=200, verbose_name='apellido'),
        ),
        migrations.AlterField(
            model_name='prof',
            name='email',
            field=models.EmailField(default='', max_length=200, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='prof',
            name='id',
            field=models.AutoField(default='', primary_key=True, serialize=False, verbose_name='id_profesional'),
        ),
        migrations.AlterField(
            model_name='prof',
            name='nombre',
            field=models.CharField(default='', max_length=200, verbose_name='nombre'),
        ),
        migrations.AlterField(
            model_name='prof',
            name='ocupacion',
            field=models.CharField(default='', max_length=200, verbose_name='ocupacion'),
        ),
        migrations.AlterField(
            model_name='prof',
            name='telefono',
            field=models.CharField(default='', max_length=200, verbose_name='telefono'),
        ),
    ]
