# Generated by Django 4.0.6 on 2022-11-18 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depil', '0002_alter_atencion_apellido_alter_atencion_coment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atencion',
            name='fecha',
            field=models.DateTimeField(auto_now=True, verbose_name='fecha'),
        ),
    ]
