# Generated by Django 4.0.6 on 2022-11-18 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depil', '0003_alter_atencion_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atencion',
            name='fecha',
            field=models.DateField(auto_now=True, verbose_name='fecha'),
        ),
    ]
