# Generated by Django 4.0.6 on 2022-11-18 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depil', '0004_alter_atencion_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atencion',
            name='fecha',
            field=models.DateField(verbose_name='fecha'),
        ),
    ]
