# Generated by Django 4.0.6 on 2022-11-18 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depil', '0005_alter_atencion_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prof',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='id_profesional'),
        ),
    ]
