# Generated by Django 4.1.3 on 2022-12-11 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('depil', '0006_alter_prof_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='atencion',
            options={},
        ),
    ]
